# permissions for end users to view grouppolicybindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grouppolicybinding-viewer-role
rules:
- apiGroups:
  - ran.openshift.io
  resources:
  - grouppolicybindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ran.openshift.io
  resources:
  - grouppolicybindings/status
  verbs:
  - get
