# permissions for end users to edit grouppolicybindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grouppolicybinding-editor-role
rules:
- apiGroups:
  - ran.openshift.io
  resources:
  - grouppolicybindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ran.openshift.io
  resources:
  - grouppolicybindings/status
  verbs:
  - get
