# permissions for end users to view grouppolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grouppolicy-viewer-role
rules:
- apiGroups:
  - ran.openshift.io
  resources:
  - grouppolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ran.openshift.io
  resources:
  - grouppolicies/status
  verbs:
  - get
