# permissions for end users to edit ransites.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ransite-editor-role
rules:
- apiGroups:
  - lcm.openshift.io
  resources:
  - ransites
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lcm.openshift.io
  resources:
  - ransites/status
  verbs:
  - get
