# permissions for end users to view ransites.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ransite-viewer-role
rules:
- apiGroups:
  - lcm.openshift.io
  resources:
  - ransites
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lcm.openshift.io
  resources:
  - ransites/status
  verbs:
  - get
