# permissions for end users to view sitebackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sitebackup-viewer-role
rules:
- apiGroups:
  - ran.openshift.io
  resources:
  - sitebackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ran.openshift.io
  resources:
  - sitebackups/status
  verbs:
  - get
