# permissions for end users to edit sitebackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sitebackup-editor-role
rules:
- apiGroups:
  - ran.openshift.io
  resources:
  - sitebackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ran.openshift.io
  resources:
  - sitebackups/status
  verbs:
  - get
